apiVersion: v1
kind: Secret
metadata:
  name: firebase-credentials
  labels:
    app: idea-board
type: Opaque
stringData:
  project-id: "YOUR_FIREBASE_PROJECT_ID"
  private-key: "YOUR_FIREBASE_PRIVATE_KEY"
  client-email: "YOUR_FIREBASE_CLIENT_EMAIL"
